# 随机化回应调查

## 概述

社会污名可能会阻止人们承认潜在的令人尴尬的行为或观点。

当人们不愿意参与关于个人敏感问题的抽样调查时，他们可能会拒绝参与。即使参与了，他们也可能会对敏感问题提供不真实的答案。

这些问题会导致**选择**偏差，给调查的解释和设计带来挑战。

为了说明社会科学家如何思考估计此类令人尴尬的行为和观点的普遍程度，本讲座描述了S. L. Warner {cite}`warner1965randomized`的一种经典方法。

Warner使用基础概率论构建了一种方法，在保护调查受访者**个人**隐私的同时，仍能估算出在一个**群体**中具有社会污名特征或从事社会污名活动的人数比例。

Warner的想法是在受访者的答案与调查制作者最终收到的**信号**之间添加**噪声**。

了解噪声的结构可以让受访者确信调查制作者无法观察到他的答案。

噪声注入程序的统计特性为受访者提供了**合理的可否认性**。

相关理念构成了现代**差分隐私**系统的基础。

(参见 https://baike.baidu.com/item/%E5%B7%AE%E5%88%86%E9%9A%90%E7%A7%81/22415732)


## Warner的策略

像往常一样，让我们导入将要使用的Python模块。

In [1]:
import numpy as np
import pandas as pd

假设人群中的每个人要么属于 A 组，要么属于 B 组。

我们想要估计属于 A 组的人口比例 $\pi$，同时保护个人受访者的隐私。

Warner {cite}`warner1965randomized` 提出并分析了以下程序：

- 从人群中有放回地抽取 $n$ 个随机样本，并对每个人进行访谈。
- 从人群中有放回地抽取 $n$ 个随机样本，并对每个人进行访谈。
- 准备一个**随机转盘**，该转盘指向字母 A 的概率为 $p$，指向字母 B 的概率为 $(1-p)$。
- 每个受试者转动随机转盘，看到一个访谈者**看不到**的结果（A 或 B）。
- 受试者说明自己是否属于转盘所指向的组。
- 如果转盘指向受试者所属的组，受试者回答"是"；否则回答"否"。
- 受试者如实回答问题。

Warner构建了一个用于估计总体中集合A所占比例的最大似然估计量。

设

- $\pi$ : 总体中A的真实概率
- $p$ : 指针指向A的概率
- $X_{i}=\begin{cases}1,\text{ 如果第}i\text{个受试者回答是}\\0,\text{ 如果第}i\text{个受试者回答否}\end{cases}$

将样本集编号，使得前$n_1$个报告"是"，而后$n-n_1$个报告"否"。

样本集的似然函数为

$$
L=\left[\pi p + (1-\pi)(1-p)\right]^{n_{1}}\left[(1-\pi) p +\pi (1-p)\right]^{n-n_{1}} 
$$ (eq:one)

似然函数的对数为：

$$
\log(L)= n_1 \log \left[\pi p + (1-\pi)(1-p)\right] + (n-n_{1}) \log \left[(1-\pi) p +\pi (1-p)\right]
$$ (eq:two)

关于 $\pi$ 最大化对数似然函数的一阶必要条件是：

$$
\frac{(n-n_1)(2p-1)}{(1-\pi) p +\pi (1-p)}=\frac{n_1 (2p-1)}{\pi p + (1-\pi)(1-p)} 
$$

或

$$
\pi p + (1-\pi)(1-p)=\frac{n_1}{n}
$$ (eq:3)

如果 $p \neq \frac{1}{2}$，则最大似然估计量（MLE）$\pi$ 为：

$$
\hat{\pi}=\frac{p-1}{2p-1}+\frac{n_1}{(2p-1)n}
$$ (eq:four)

我们计算最大似然估计量 $\hat \pi$ 的均值和方差为：

$$
\begin{aligned}
\mathbb{E}(\hat{\pi})&= \frac{1}{2 p-1}\left[p-1+\frac{1}{n} \sum_{i=1}^{n} \mathbb{E} X_i \right] \\
&=\frac{1}{2 p-1} \left[ p -1 + \pi p + (1-\pi)(1-p)\right] \\
&=\pi
\end{aligned}
$$ (eq:five)

以及

$$
\begin{aligned}
Var(\hat{\pi})&=\frac{n Var(X_i)}{(2p - 1 )^2 n^2} \\
&= \frac{\left[\pi p + (1-\pi)(1-p)\right]\left[(1-\pi) p +\pi (1-p)\right]}{(2p - 1 )^2 n^2}\\
&=\frac{\frac{1}{4}+(2 p^2 - 2 p +\frac{1}{2})(- 2 \pi^2 + 2 \pi -\frac{1}{2})}{(2p - 1 )^2 n^2}\\
&=\frac{1}{n}\left[\frac{1}{16(p-\frac{1}{2})^2}-(\pi-\frac{1}{2})^2 \right]
\end{aligned}
$$ (eq:six)

方程 {eq}`eq:five` 表明 $\hat{\pi}$ 是 $\pi$ 的**无偏估计量**，而方程 {eq}`eq:six` 告诉我们估计量的方差。

为了计算置信区间，首先将 {eq}`eq:six` 重写为：

$$
Var(\hat{\pi})=\frac{\frac{1}{4}-(\pi-\frac{1}{2})^2}{n}+\frac{\frac{1}{16(p-\frac{1}{2})^2}-\frac{1}{4}}{n}
$$ (eq:seven)

这个方程表明 $\hat{\pi}$ 的方差可以表示为抽样方差和随机设备方差的和。

从上述表达式中我们可以发现：

- 当 $p$ 为 $\frac{1}{2}$ 时，表达式 {eq}`eq:one` 退化为一个常数。

- 当 $p$ 为 $1$ 或 $0$ 时，随机化估计退化为不含随机抽样的估计量。

我们将只讨论 $p \in (\frac{1}{2},1)$ 的情况

（$p \in (0,\frac{1}{2})$ 的情况是对称的）。

从表达式 {eq}`eq:five` 和 {eq}`eq:seven` 我们可以推导出：

- 随着 $p$ 的增加，$\hat{\pi}$ 的均方误差(MSE)减小。

## 比较两种调查设计

让我们比较前面的随机化回答法与一个简化的非随机化回答法。

在我们的非随机化回答法中，我们假设：

- A组成员以概率 $T_a$ 说真话，而B组成员以概率 $T_b$ 说真话
- $Y_i$ 为 $1$ 或 $0$，取决于样本中第 $i$ 个成员的报告是否属于A组。

那么我们可以估计 $\pi$ 为：

$$
\hat{\pi}=\frac{\sum_{i=1}^{n}Y_i}{n}
$$ (eq:eight)

我们计算该估计量的期望值、偏差和方差为：

$$
\begin{aligned}
\mathbb{E}(\hat{\pi})&=\pi T_a + \left[ (1-\pi)(1-T_b)\right]\\
\end{aligned}
$$ (eq:nine)

$$
\begin{aligned}
Bias(\hat{\pi})&=\mathbb{E}(\hat{\pi}-\pi)\\
&=\pi [T_a + T_b -2 ] + [1- T_b] \\
\end{aligned}
$$ (eq:ten)

$$
\begin{aligned}
Var(\hat{\pi})&=\frac{ \left[ \pi T_a + (1-\pi)(1-T_b)\right]  \left[1- \pi T_a -(1-\pi)(1-T_b)\right] }{n}
\end{aligned}
$$ (eq:eleven)

定义如下量是有用的：

$$
\text{MSE 比率}=\frac{\text{随机化的均方误差}}{\text{常规的均方误差}}
$$

我们可以计算不同参数值下不同调查设计的MSE比率。

以下Python代码计算了我们想要观察的对象，以便在不同的$\pi_A$和$n$值下进行比较：

In [2]:
class Comparison:
    def __init__(self, A, n):
        self.A = A
        self.n = n
        TaTb = np.array([[0.95,  1], [0.9,   1], [0.7,    1], 
                         [0.5,   1], [1,  0.95], [1,    0.9], 
                         [1,   0.7], [1,   0.5], [0.95, 0.95], 
                         [0.9, 0.9], [0.7, 0.7], [0.5,  0.5]])
        self.p_arr = np.array([0.6, 0.7, 0.8, 0.9])
        self.p_map = dict(zip(self.p_arr, [f"MSE 比率: p = {x}" for x in self.p_arr]))
        self.template = pd.DataFrame(columns=self.p_arr)
        self.template[['T_a','T_b']] = TaTb
        self.template['Bias'] = None
    
    def theoretical(self):
        A = self.A
        n = self.n
        df = self.template.copy()
        df['Bias'] = A * (df['T_a'] + df['T_b'] - 2) + (1 - df['T_b'])
        for p in self.p_arr:
            df[p] = (1 / (16 * (p - 1/2)**2) - (A - 1/2)**2) / n / \
                    (df['Bias']**2 + ((A * df['T_a'] + (1 - A) * (1 - df['T_b'])) * (1 - A * df['T_a'] - (1 - A) * (1 - df['T_b'])) / n))
            df[p] = df[p].round(2)
        df = df.set_index(["T_a", "T_b", "Bias"]).rename(columns=self.p_map)
        return df
        
    def MCsimulation(self, size=1000, seed=123456):
        A = self.A
        n = self.n
        df = self.template.copy()
        rng = np.random.default_rng(seed)
        sample = rng.random((size, self.n)) <= A
        random_device = rng.random((size, n))
        mse_rd = {}
        for p in self.p_arr:
            spinner = random_device <= p
            rd_answer = sample * spinner + (1 - sample) * (1 - spinner)
            n1 = rd_answer.sum(axis=1)
            pi_hat = (p - 1) / (2 * p - 1) + n1 / n / (2 * p - 1)
            mse_rd[p] = np.sum((pi_hat - A)**2)
        for inum, irow in df.iterrows():
            truth_a = rng.random((size, self.n)) <= irow.T_a
            truth_b = rng.random((size, self.n)) <= irow.T_b
            trad_answer = sample * truth_a + (1 - sample) * (1 - truth_b)
            pi_trad = trad_answer.sum(axis=1) / n
            df.loc[inum, 'Bias'] = pi_trad.mean() - A
            mse_trad = np.sum((pi_trad - A)**2)
            for p in self.p_arr:
                df.loc[inum, p] = (mse_rd[p] / mse_trad).round(2)
        df = df.set_index(["T_a", "T_b", "Bias"]).rename(columns=self.p_map)
        return df

让我们使用以下参数值来运行代码

- $\pi_A=0.6$
- $n=1000$

我们可以使用上述公式理论上生成MSE比率。

我们也可以对MSE比率进行蒙特卡洛模拟。

In [3]:
cp1 = Comparison(0.6, 1000)
df1_theoretical = cp1.theoretical()
df1_theoretical

                 MSE 比率: p = 0.6  MSE 比率: p = 0.7  MSE 比率: p = 0.8  \
T_a  T_b  Bias
0.95 1.00 -0.03             5.45             1.36             0.60
0.90 1.00 -0.06             1.62             0.40             0.18
0.70 1.00 -0.18             0.19             0.05             0.02
0.50 1.00 -0.30             0.07             0.02             0.01
1.00 0.95  0.02             9.82             2.44             1.08
     0.90  0.04             3.41             0.85             0.37
     0.70  0.12             0.43             0.11             0.05
     0.50  0.20             0.16             0.04             0.02
0.95 0.95 -0.01            18.25             4.54             2.00
0.90 0.90 -0.02             9.70             2.41             1.06
0.70 0.70 -0.06             1.62             0.40             0.18
0.50 0.50 -0.10             0.61             0.15             0.07

                 MSE 比率: p = 0.9
T_a  T_b  Bias
0.95 1.00 -0.03             0.33
0.90 1.00 -0.06             0.10
0.70 1.00 -0.18             0.01
0.50 1.00 -0.30             0.00
1.00 0.95  0.02             0.60
     0.90  0.04             0.21
     0.70  0.12             0.03
     0.50  0.20             0.01
0.95 0.95 -0.01             1.11
0.90 0.90 -0.02             0.59
0.70 0.70 -0.06             0.10
0.50 0.50 -0.10             0.04

In [4]:
df1_mc = cp1.MCsimulation()
df1_mc

                    MSE 比率: p = 0.6 MSE 比率: p = 0.7 MSE 比率: p = 0.8  \
T_a  T_b  Bias
0.95 1.00 -0.030191            5.37            1.34            0.62
0.90 1.00 -0.060081            1.61             0.4            0.19
0.70 1.00 -0.180543            0.19            0.05            0.02
0.50 1.00 -0.29977             0.07            0.02            0.01
1.00 0.95  0.019297           10.18            2.54            1.18
     0.90  0.03985             3.41            0.85             0.4
     0.70  0.119465            0.43            0.11            0.05
     0.50  0.199398            0.16            0.04            0.02
0.95 0.95 -0.010326           16.91            4.21            1.96
0.90 0.90 -0.019838            9.67            2.41            1.12
0.70 0.70 -0.06076             1.58            0.39            0.18
0.50 0.50 -0.100091            0.61            0.15            0.07

                    MSE 比率: p = 0.9
T_a  T_b  Bias
0.95 1.00 -0.030191            0.35
0.90 1.00 -0.060081            0.11
0.70 1.00 -0.180543            0.01
0.50 1.00 -0.29977              0.0
1.00 0.95  0.019297            0.67
     0.90  0.03985             0.22
     0.70  0.119465            0.03
     0.50  0.199398            0.01
0.95 0.95 -0.010326             1.1
0.90 0.90 -0.019838            0.63
0.70 0.70 -0.06076              0.1
0.50 0.50 -0.100091            0.04

理论计算很好地预测了蒙特卡洛结果。

我们看到在许多情况下，特别是当偏差不小时，随机抽样方法的均方误差比非随机抽样方法要小。

随着 $p$ 的增加，这些差异变得更大。

通过调整参数 $\pi_A$ 和 $n$，我们可以研究不同情况下的结果。

例如，对于Warner {cite}`warner1965randomized`描述的另一种情况：

- $\pi_A=0.5$
- $n=1000$

我们可以使用以下代码

In [5]:
cp2 = Comparison(0.5, 1000)
df2_theoretical = cp2.theoretical()
df2_theoretical

                  MSE 比率: p = 0.6  MSE 比率: p = 0.7  MSE 比率: p = 0.8  \
T_a  T_b  Bias
0.95 1.00 -0.025             7.15             1.79             0.79
0.90 1.00 -0.050             2.27             0.57             0.25
0.70 1.00 -0.150             0.27             0.07             0.03
0.50 1.00 -0.250             0.10             0.02             0.01
1.00 0.95  0.025             7.15             1.79             0.79
     0.90  0.050             2.27             0.57             0.25
     0.70  0.150             0.27             0.07             0.03
     0.50  0.250             0.10             0.02             0.01
0.95 0.95  0.000            25.00             6.25             2.78
0.90 0.90  0.000            25.00             6.25             2.78
0.70 0.70  0.000            25.00             6.25             2.78
0.50 0.50  0.000            25.00             6.25             2.78

                  MSE 比率: p = 0.9
T_a  T_b  Bias
0.95 1.00 -0.025             0.45
0.90 1.00 -0.050             0.14
0.70 1.00 -0.150             0.02
0.50 1.00 -0.250             0.01
1.00 0.95  0.025             0.45
     0.90  0.050             0.14
     0.70  0.150             0.02
     0.50  0.250             0.01
0.95 0.95  0.000             1.56
0.90 0.90  0.000             1.56
0.70 0.70  0.000             1.56
0.50 0.50  0.000             1.56

In [6]:
df2_mc = cp2.MCsimulation()
df2_mc

                    MSE 比率: p = 0.6 MSE 比率: p = 0.7 MSE 比率: p = 0.8  \
T_a  T_b  Bias
0.95 1.00 -0.025243            7.17            1.78            0.83
0.90 1.00 -0.050271            2.29            0.57            0.27
0.70 1.00 -0.150607            0.28            0.07            0.03
0.50 1.00 -0.250029             0.1            0.03            0.01
1.00 0.95  0.024097            7.63            1.89            0.89
     0.90  0.049794            2.33            0.58            0.27
     0.70  0.149336            0.28            0.07            0.03
     0.50  0.249073             0.1            0.03            0.01
0.95 0.95 -0.000357           23.53            5.84            2.74
0.90 0.90  0.000068           25.04            6.21            2.91
0.70 0.70 -0.00079            26.04            6.46            3.03
0.50 0.50 -0.000077           24.26            6.02            2.82

                    MSE 比率: p = 0.9
T_a  T_b  Bias
0.95 1.00 -0.025243            0.47
0.90 1.00 -0.050271            0.15
0.70 1.00 -0.150607            0.02
0.50 1.00 -0.250029            0.01
1.00 0.95  0.024097             0.5
     0.90  0.049794            0.15
     0.70  0.149336            0.02
     0.50  0.249073            0.01
0.95 0.95 -0.000357            1.54
0.90 0.90  0.000068            1.64
0.70 0.70 -0.00079              1.7
0.50 0.50 -0.000077            1.59

我们还可以重新审视Warner {cite}`warner1965randomized`结论部分的一个计算，其中

- $\pi_A=0.6$
- $n=2000$

我们使用以下代码

In [7]:
cp3 = Comparison(0.6, 2000)
df3_theoretical = cp3.theoretical()
df3_theoretical

                 MSE 比率: p = 0.6  MSE 比率: p = 0.7  MSE 比率: p = 0.8  \
T_a  T_b  Bias
0.95 1.00 -0.03             3.05             0.76             0.33
0.90 1.00 -0.06             0.84             0.21             0.09
0.70 1.00 -0.18             0.10             0.02             0.01
0.50 1.00 -0.30             0.03             0.01             0.00
1.00 0.95  0.02             6.03             1.50             0.66
     0.90  0.04             1.82             0.45             0.20
     0.70  0.12             0.22             0.05             0.02
     0.50  0.20             0.08             0.02             0.01
0.95 0.95 -0.01            14.12             3.51             1.55
0.90 0.90 -0.02             5.98             1.49             0.66
0.70 0.70 -0.06             0.84             0.21             0.09
0.50 0.50 -0.10             0.31             0.08             0.03

                 MSE 比率: p = 0.9
T_a  T_b  Bias
0.95 1.00 -0.03             0.19
0.90 1.00 -0.06             0.05
0.70 1.00 -0.18             0.01
0.50 1.00 -0.30             0.00
1.00 0.95  0.02             0.37
     0.90  0.04             0.11
     0.70  0.12             0.01
     0.50  0.20             0.00
0.95 0.95 -0.01             0.86
0.90 0.90 -0.02             0.36
0.70 0.70 -0.06             0.05
0.50 0.50 -0.10             0.02

In [8]:
df3_mc = cp3.MCsimulation()
df3_mc

                    MSE 比率: p = 0.6 MSE 比率: p = 0.7 MSE 比率: p = 0.8  \
T_a  T_b  Bias
0.95 1.00 -0.029752            3.04            0.74            0.33
0.90 1.00 -0.059862            0.82             0.2            0.09
0.70 1.00 -0.179691            0.09            0.02            0.01
0.50 1.00 -0.299452            0.03            0.01             0.0
1.00 0.95  0.020192            5.85            1.43            0.64
     0.90  0.040388            1.75            0.43            0.19
     0.70  0.120138            0.21            0.05            0.02
     0.50  0.199962            0.08            0.02            0.01
0.95 0.95 -0.009622           14.35            3.51            1.57
0.90 0.90 -0.019695            6.05            1.48            0.66
0.70 0.70 -0.059774            0.83             0.2            0.09
0.50 0.50 -0.1                  0.3            0.07            0.03

                    MSE 比率: p = 0.9
T_a  T_b  Bias
0.95 1.00 -0.029752            0.18
0.90 1.00 -0.059862            0.05
0.70 1.00 -0.179691            0.01
0.50 1.00 -0.299452             0.0
1.00 0.95  0.020192            0.35
     0.90  0.040388             0.1
     0.70  0.120138            0.01
     0.50  0.199962             0.0
0.95 0.95 -0.009622            0.85
0.90 0.90 -0.019695            0.36
0.70 0.70 -0.059774            0.05
0.50 0.50 -0.1                 0.02

显然，随着 $n$ 的增加，随机化回应法在更多情况下表现更好。

## 结束语

{doc}`这个QuantEcon讲座<util_rand_resp>`描述了一些其他的随机化回应调查方法。

该讲座介绍了Lars Ljungqvist {cite}`ljungqvist1993unified`对这些替代方案进行的功利主义分析。